<?php

namespace AppBundle\Repository;

/**
 * AnalysisCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
