<?php

namespace AppBundle\Repository;

/**
 * CriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriaRepository extends \Doctrine\ORM\EntityRepository {

    private $entityName = 'AppBundle:Criteria';
 
    public function getFiltered(array $filters) : array {
        $queryBuilder = $this->createQueryBuilder('c')
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName());

        if (isset($filters['id'])) $queryBuilder->andWhere('c.id = :id');
        
        if (isset($filters['score'])) $queryBuilder->andWhere('c.score = :score');

        if (isset($filters['keyword'])) {
            $queryBuilder->andWhere('c.keyword LIKE :keyword');
            $filters['keyword'] = '%' . $filters['keyword'] . '%';
        }

        if (count($filters)) $queryBuilder->setParameters($filters);

        return $queryBuilder->getQuery()->getResult();
    }

}
