<?php

namespace AppBundle\Repository;

/**
 * EmphasizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmphasizerRepository extends \Doctrine\ORM\EntityRepository {
    
    private $entityName = 'AppBundle:Emphasizer';
 
    public function getFiltered(array $filters) : array {
        $queryBuilder = $this->createQueryBuilder('c')
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName());

        if (isset($filters['id'])) $queryBuilder->andWhere('c.id = :id');
        
        if (isset($filters['score_modifier'])) $queryBuilder->andWhere('c.scoreModifier = :score_modifier');

        if (isset($filters['name'])) {
            $queryBuilder->andWhere('c.name LIKE :name');
            $filters['name'] = '%' . $filters['name'] . '%';
        }

        if (count($filters)) $queryBuilder->setParameters($filters);

        return $queryBuilder->getQuery()->getResult();
    }

}
