<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository {

    private $entityName = 'AppBundle:Review';

    public function getUnanalyzedReviews() : array {
        $queryBuilder = $this->createQueryBuilder('r');

        $queryBuilder
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName())
            ->where($queryBuilder->expr()->isNull('r.totalScore'));

        return $queryBuilder->getQuery()->getResult();
    }

    public function getFiltered(array $filters) : array {
        $queryBuilder = $this->createQueryBuilder('r')
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName());

        if (isset($filters['id'])) $queryBuilder->andWhere('r.id = :id');

        if (isset($filters['total_score'])) {
            $firstChar = $filters['total_score'][0];

            if (! is_numeric($firstChar) && $firstChar != '-' && $firstChar != '+')
                $filters['total_score'] = (int)substr($filters['total_score'], 1);
                if ($firstChar == '<' || $firstChar == '>' || $firstChar == '=')
                    $operation = $firstChar;
            else 
                $operation = '=';

            $queryBuilder->andWhere('r.totalScore '.$operation.' :total_score');
        }

        if (isset($filters['text'])) {
            $queryBuilder->andWhere('r.text LIKE :text');
            $filters['text'] = '%' . $filters['text'] . '%';
        }

        if (count($filters)) $queryBuilder->setParameters($filters);

        return $queryBuilder->getQuery()->getResult();
    }

}
