<?php

namespace AppBundle\Repository;

/**
 * TopicAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicAliasRepository extends \Doctrine\ORM\EntityRepository {

    private $entityName = 'AppBundle:TopicAlias';
 
    public function getFiltered(array $filters) : array {
        $queryBuilder = $this->createQueryBuilder('a')
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName())
            ->join('a.topic', 'topics');

        if (isset($filters['id']))
            $queryBuilder->andWhere('a.id = :id');

        if (isset($filters['topic_name'])) {
            $queryBuilder->andWhere('topics.name LIKE :topic_name');
            $filters['topic_name'] = '%' . $filters['topic_name'] . '%';
        }

        if (isset($filters['alias'])) {
            $queryBuilder->andWhere('a.alias LIKE :alias');
            $filters['alias'] = '%' . $filters['alias'] . '%';
        }

        if (count($filters)) $queryBuilder->setParameters($filters);

        return $queryBuilder->add('orderBy', 'topics.name ASC, a.alias ASC')->getQuery()->getResult();
    }
}
