<?php

namespace AppBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository {

    private $entityName = 'AppBundle:Topic';
 
    public function getFiltered(array $filters) : array {
        $queryBuilder = $this->createQueryBuilder('t')
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName());

        if (isset($filters['id']))
            $queryBuilder->andWhere('t.id = :id');

        if (isset($filters['priority']))
            $queryBuilder->andWhere('t.priority = :priority');
        
        if (isset($filters['alias'])) {
            $queryBuilder->join('t.aliases', 'aliases')->andWhere('aliases.alias LIKE :alias');
            $filters['alias'] = '%' . $filters['alias'] . '%';
        }

        if (isset($filters['name'])) {
            $queryBuilder->andWhere('t.name LIKE :name');
            $filters['name'] = '%' . $filters['name'] . '%';
        }

        if (count($filters)) $queryBuilder->setParameters($filters);

        return $queryBuilder->getQuery()->getResult();
    }

}
